name: stats
channels:
  - plotly
  - conda-forge
  - r
  - anaconda
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=18.2.0
  - automat=0.7.0
  - backcall=0.1.0
  - binutils_impl_linux-64=2.28.1
  - binutils_linux-64=7.2.0
  - blas=1.0
  - bleach=2.1.4
  - bwidget=1.9.11
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - cffi=1.11.5
  - chardet=3.0.4
  - constantly=15.1.0
  - cryptography=2.3.1
  - curl=7.61.0
  - cycler=0.10.0
  - dbus=1.13.2
  - decorator=4.3.0
  - entrypoints=0.2.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gcc_impl_linux-64=7.2.0
  - gcc_linux-64=7.2.0
  - gfortran_impl_linux-64=7.2.0
  - gfortran_linux-64=7.2.0
  - glib=2.56.2
  - gmp=6.1.2
  - graphite2=1.3.12
  - gsl=2.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.2.0
  - gxx_linux-64=7.2.0
  - harfbuzz=1.8.8
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - imageio=2.3.0
  - incremental=17.5.0
  - intel-openmp=2018.0.3
  - ipykernel=4.9.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.1
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - krb5=1.16.1
  - libcurl=7.61.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.34
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - lxml=4.2.5
  - make=4.2.1
  - markupsafe=1.0
  - mistune=0.8.3
  - mkl=2018.0.3
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.6.0
  - numpy=1.15.1
  - numpy-base=1.15.1
  - olefile=0.45.1
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.3.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pillow=5.2.0
  - pip=10.0.1
  - pixman=0.34.0
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pysocks=1.6.8
  - python=3.7.0
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pyzmq=17.1.2
  - qt=5.6.3
  - readline=7.0
  - requests=2.19.1
  - retrying=1.3.3
  - rpy2=2.9.1
  - scipy=1.1.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.11.0
  - sqlite=3.24.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.8
  - tktable=2.10
  - tornado=5.1.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - urllib3=1.23
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.1
  - widgetsnbextension=3.4.1
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.5.0
  - certifi=2018.8.24
  - libiconv=1.15
  - libxslt=1.1.32
  - matplotlib=2.2.3
  - openssl=1.0.2p
  - python-docx=0.8.7
  - qtconsole=4.4.1
  - scikit-learn=0.20.1
  - plotly=3.2.0
  - _r-mutex=1.0.0
  - r-assertthat=0.2.0
  - r-base=3.5.0
  - r-bh=1.66.0_1
  - r-bindr=0.1.1
  - r-bindrcpp=0.2.2
  - r-bit=1.1_12
  - r-bit64=0.9_7
  - r-blob=1.1.1
  - r-cli=1.0.0
  - r-crayon=1.3.4
  - r-dbi=0.8
  - r-dbplyr=1.2.1
  - r-digest=0.6.15
  - r-dplyr=0.7.4
  - r-glue=1.2.0
  - r-magrittr=1.5
  - r-memoise=1.1.0
  - r-pillar=1.2.1
  - r-pkgconfig=2.0.1
  - r-plogr=0.2.0
  - r-prettyunits=1.0.2
  - r-purrr=0.2.4
  - r-r6=2.2.2
  - r-rcpp=0.12.16
  - r-rlang=0.2.0
  - r-rsqlite=2.1.0
  - r-tibble=1.4.2
  - r-tidyselect=0.2.4
  - r-utf8=1.1.3

